<?php

/**
 * @file
 * Module used to respond to OAI requests.
 */

/**
 * Implements hook_menu().
 */
function islandora_oai_menu() {
  $items = array();

  $items['admin/islandora/tools/islandora-oai'] = array(
    'title' => 'Islandora OAI',
    'description' => 'Configure the Islandora OAI module',
    'file' => 'includes/admin.form.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_oai_admin_form'),
    'access arguments' => array('access administration pages'),
  );
  $items['admin/islandora/tools/islandora-oai/configure'] = array(
    'title' => 'Islandora OAI Settings',
    'description' => 'Configure the Islandora OAI module',
    'file' => 'includes/admin.form.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_oai_admin_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/islandora/tools/islandora-oai/files'] = array(
    'title' => 'File Management',
    'description' => 'Manage the upload files for Islandora OAI',
    'file' => 'includes/admin.form.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_oai_file_management_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items[variable_get('islandora_oai_path', 'oai2')] = array(
    'title' => 'OAI2',
    'page callback' => 'islandora_oai_parse_request',
    'file' => 'includes/request.inc',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_islandora_oai_get_xsl_files().
 */
function islandora_oai_islandora_oai_get_xsl_files() {
  $files = file_scan_directory(drupal_get_path('module', 'islandora_oai') . '/transforms/', '/.*\.xslt?$/');

  $transform_options = array();

  foreach ($files as $file) {
    $transform_options[$file->uri] = $file->filename;
  }

  $oai_uploaded_files = array();
  $upload_path = 'public://islandora_oai_xsls';
  $uploaded_files = file_scan_directory($upload_path, '/.*\.xslt?$/');

  foreach ($uploaded_files as $up_file) {
    $oai_uploaded_files[$up_file->uri] = $up_file->filename;
  }

  foreach ($oai_uploaded_files as $key => $file) {
    if (!in_array($file, $transform_options)) {
      $transform_options[$key] = $file;
    }
  }
  return $transform_options;
}


/**
 * Implements hook_cron().
 */
function islandora_oai_cron() {
  $expire_seconds = variable_get('islandora_oai_expire_time', '86400');
  $expire_time = time() - $expire_seconds;
  db_query("DELETE FROM {islandora_oai_tokens} WHERE timestamp < :expire_time", array(':expire_time' => $expire_time));
}
